"""
Report generator — produces a Markdown damage assessment report.
"""
from __future__ import annotations

import textwrap
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

import torch
from torch import Tensor

from src.explainability.dii import interpret_dii


def generate_report(
    dii_score: float,
    phi_norm: Tensor,
    feature_names: Optional[List[str]] = None,
    query_metadata: Optional[Dict] = None,
    output_path: Optional[str] = None,
) -> str:
    """Generate a human-readable Markdown damage assessment report.

    Args:
        dii_score:      Scalar DII_improved value.
        phi_norm:       ``(k,)`` normalised SHAP importance weights.
        feature_names:  Names for each feature channel.
        query_metadata: Dict with keys: location, start_date, end_date, task.
        output_path:    If given, write report to this file path.

    Returns:
        Report as a Markdown string.
    """
    if feature_names is None:
        feature_names = ["Buildings", "Roads", "Vegetation", "Infrastructure"]

    severity = interpret_dii(dii_score)
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    meta = query_metadata or {}

    # ── Feature importance table ─────────────────────────────────────
    table_rows = []
    for name, weight in zip(feature_names, phi_norm.tolist()):
        bar = "█" * int(weight * 20)
        table_rows.append(f"| {name:<20} | {weight:.4f} | {bar}")
    table = "\n".join(table_rows)

    report = textwrap.dedent(f"""
    # UGIF — Disaster Damage Assessment Report

    **Generated:** {now}
    **Location:** {meta.get('location', 'Not specified')}
    **Period:** {meta.get('start_date', 'N/A')} → {meta.get('end_date', 'N/A')}
    **Task:** {meta.get('task', 'Change Detection')}

    ---

    ## Disaster Impact Index (DII)

    | Metric        | Value           |
    |---------------|-----------------|
    | DII_improved  | **{dii_score:.4f}** |
    | Severity      | **{severity}**  |

    > DII > 1 indicates damage (pre-disaster features exceeded post-disaster).
    > DII < 1 may indicate recovery or vegetation regrowth.

    ---

    ## Feature Importance (SHAP φᵢⁿᵒʳᵐ)

    | Feature              | Weight | Relative Impact           |
    |----------------------|--------|---------------------------|
    {table}

    ---

    ## Interpretation

    The model detected **{severity.lower()}** in the analysed region.
    The most impacted feature category is **{feature_names[phi_norm.argmax().item()]}**
    with a normalised SHAP weight of **{phi_norm.max().item():.4f}**.

    ---
    *Generated by UGIF — Unified Geospatial Intelligence Framework*
    """).strip()

    if output_path:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        Path(output_path).write_text(report)
        print(f"Report saved to {output_path}")

    return report


if __name__ == "__main__":
    import torch
    phi = torch.tensor([0.40, 0.25, 0.20, 0.15])
    report = generate_report(
        dii_score=2.1,
        phi_norm=phi,
        query_metadata={
            "location": "Chennai, India",
            "start_date": "2023-08-01",
            "end_date": "2023-08-31",
            "task": "Flood damage assessment",
        },
        output_path="outputs/sample_report.md",
    )
    print(report)
